<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFTNibDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFTNibDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFTNibDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFTNibDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFTNibDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'FTNibDx',
    'container.build_id' => 'ac66c0b8',
    'container.build_time' => 1717620323,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFTNibDx');
