<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEp7ipZL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEp7ipZL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEp7ipZL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEp7ipZL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEp7ipZL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ep7ipZL',
    'container.build_id' => 'bdefa9ee',
    'container.build_time' => 1717619112,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEp7ipZL');
