<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVJZIgQk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVJZIgQk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVJZIgQk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVJZIgQk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVJZIgQk\App_KernelDevDebugContainer([
    'container.build_hash' => 'VJZIgQk',
    'container.build_id' => '527f3605',
    'container.build_time' => 1717753743,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVJZIgQk');
